#!/bin/bash

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.go')

if [[ $STAGED_GO_FILES != "" ]]; then
    echo "[pre-commit] fmt'ing staged files..."

    for file in $STAGED_GO_FILES; do
        gofmt -w -s $file
        misspell -w $file
        goimports -w -local github.com/commercionetwork/commercionetwork $file

        git add $file
    done
fi