// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: commercionetwork/commerciomint/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryEtpRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (m *QueryEtpRequest) Reset()         { *m = QueryEtpRequest{} }
func (m *QueryEtpRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEtpRequest) ProtoMessage()    {}
func (*QueryEtpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{0}
}
func (m *QueryEtpRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEtpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEtpRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEtpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEtpRequest.Merge(m, src)
}
func (m *QueryEtpRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEtpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEtpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEtpRequest proto.InternalMessageInfo

func (m *QueryEtpRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type QueryEtpRequestByOwner struct {
	Owner string `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
}

func (m *QueryEtpRequestByOwner) Reset()         { *m = QueryEtpRequestByOwner{} }
func (m *QueryEtpRequestByOwner) String() string { return proto.CompactTextString(m) }
func (*QueryEtpRequestByOwner) ProtoMessage()    {}
func (*QueryEtpRequestByOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{1}
}
func (m *QueryEtpRequestByOwner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEtpRequestByOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEtpRequestByOwner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEtpRequestByOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEtpRequestByOwner.Merge(m, src)
}
func (m *QueryEtpRequestByOwner) XXX_Size() int {
	return m.Size()
}
func (m *QueryEtpRequestByOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEtpRequestByOwner.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEtpRequestByOwner proto.InternalMessageInfo

func (m *QueryEtpRequestByOwner) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryEtpResponse struct {
	Position *Position `protobuf:"bytes,1,opt,name=Position,proto3" json:"Position,omitempty"`
}

func (m *QueryEtpResponse) Reset()         { *m = QueryEtpResponse{} }
func (m *QueryEtpResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEtpResponse) ProtoMessage()    {}
func (*QueryEtpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{2}
}
func (m *QueryEtpResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEtpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEtpResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEtpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEtpResponse.Merge(m, src)
}
func (m *QueryEtpResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEtpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEtpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEtpResponse proto.InternalMessageInfo

func (m *QueryEtpResponse) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type QueryEtpsRequest struct {
}

func (m *QueryEtpsRequest) Reset()         { *m = QueryEtpsRequest{} }
func (m *QueryEtpsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEtpsRequest) ProtoMessage()    {}
func (*QueryEtpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{3}
}
func (m *QueryEtpsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEtpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEtpsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEtpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEtpsRequest.Merge(m, src)
}
func (m *QueryEtpsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryEtpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEtpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEtpsRequest proto.InternalMessageInfo

type QueryEtpsResponse struct {
	Positions []*Position `protobuf:"bytes,1,rep,name=Positions,proto3" json:"Positions,omitempty"`
}

func (m *QueryEtpsResponse) Reset()         { *m = QueryEtpsResponse{} }
func (m *QueryEtpsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryEtpsResponse) ProtoMessage()    {}
func (*QueryEtpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{4}
}
func (m *QueryEtpsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryEtpsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryEtpsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryEtpsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEtpsResponse.Merge(m, src)
}
func (m *QueryEtpsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryEtpsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEtpsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEtpsResponse proto.InternalMessageInfo

func (m *QueryEtpsResponse) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type QueryConversionRate struct {
}

func (m *QueryConversionRate) Reset()         { *m = QueryConversionRate{} }
func (m *QueryConversionRate) String() string { return proto.CompactTextString(m) }
func (*QueryConversionRate) ProtoMessage()    {}
func (*QueryConversionRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{5}
}
func (m *QueryConversionRate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConversionRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConversionRate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConversionRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConversionRate.Merge(m, src)
}
func (m *QueryConversionRate) XXX_Size() int {
	return m.Size()
}
func (m *QueryConversionRate) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConversionRate.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConversionRate proto.InternalMessageInfo

type QueryConversionRateResponse struct {
	Rate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=rate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"rate"`
}

func (m *QueryConversionRateResponse) Reset()         { *m = QueryConversionRateResponse{} }
func (m *QueryConversionRateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryConversionRateResponse) ProtoMessage()    {}
func (*QueryConversionRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{6}
}
func (m *QueryConversionRateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryConversionRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryConversionRateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryConversionRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryConversionRateResponse.Merge(m, src)
}
func (m *QueryConversionRateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryConversionRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryConversionRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryConversionRateResponse proto.InternalMessageInfo

type QueryFreezePeriod struct {
}

func (m *QueryFreezePeriod) Reset()         { *m = QueryFreezePeriod{} }
func (m *QueryFreezePeriod) String() string { return proto.CompactTextString(m) }
func (*QueryFreezePeriod) ProtoMessage()    {}
func (*QueryFreezePeriod) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{7}
}
func (m *QueryFreezePeriod) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFreezePeriod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFreezePeriod.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFreezePeriod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFreezePeriod.Merge(m, src)
}
func (m *QueryFreezePeriod) XXX_Size() int {
	return m.Size()
}
func (m *QueryFreezePeriod) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFreezePeriod.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFreezePeriod proto.InternalMessageInfo

type QueryFreezePeriodResponse struct {
	FreezePeriod string `protobuf:"bytes,1,opt,name=freeze_period,json=freezePeriod,proto3" json:"freeze_period,omitempty"`
}

func (m *QueryFreezePeriodResponse) Reset()         { *m = QueryFreezePeriodResponse{} }
func (m *QueryFreezePeriodResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFreezePeriodResponse) ProtoMessage()    {}
func (*QueryFreezePeriodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad254ae0ff13a4bf, []int{8}
}
func (m *QueryFreezePeriodResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFreezePeriodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFreezePeriodResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFreezePeriodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFreezePeriodResponse.Merge(m, src)
}
func (m *QueryFreezePeriodResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFreezePeriodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFreezePeriodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFreezePeriodResponse proto.InternalMessageInfo

func (m *QueryFreezePeriodResponse) GetFreezePeriod() string {
	if m != nil {
		return m.FreezePeriod
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryEtpRequest)(nil), "commercionetwork.commercionetwork.commerciomint.QueryEtpRequest")
	proto.RegisterType((*QueryEtpRequestByOwner)(nil), "commercionetwork.commercionetwork.commerciomint.QueryEtpRequestByOwner")
	proto.RegisterType((*QueryEtpResponse)(nil), "commercionetwork.commercionetwork.commerciomint.QueryEtpResponse")
	proto.RegisterType((*QueryEtpsRequest)(nil), "commercionetwork.commercionetwork.commerciomint.QueryEtpsRequest")
	proto.RegisterType((*QueryEtpsResponse)(nil), "commercionetwork.commercionetwork.commerciomint.QueryEtpsResponse")
	proto.RegisterType((*QueryConversionRate)(nil), "commercionetwork.commercionetwork.commerciomint.QueryConversionRate")
	proto.RegisterType((*QueryConversionRateResponse)(nil), "commercionetwork.commercionetwork.commerciomint.QueryConversionRateResponse")
	proto.RegisterType((*QueryFreezePeriod)(nil), "commercionetwork.commercionetwork.commerciomint.QueryFreezePeriod")
	proto.RegisterType((*QueryFreezePeriodResponse)(nil), "commercionetwork.commercionetwork.commerciomint.QueryFreezePeriodResponse")
}

func init() {
	proto.RegisterFile("commercionetwork/commerciomint/query.proto", fileDescriptor_ad254ae0ff13a4bf)
}

var fileDescriptor_ad254ae0ff13a4bf = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xce, 0xa4, 0xad, 0xb4, 0xc7, 0x5a, 0x75, 0x5a, 0xa5, 0xae, 0xb2, 0xad, 0xa3, 0x14, 0xff,
	0xb2, 0x43, 0x2b, 0x22, 0xde, 0xb5, 0x6b, 0xa2, 0x44, 0x04, 0x6b, 0x40, 0x04, 0x11, 0xca, 0x36,
	0x9d, 0xae, 0x4b, 0x9b, 0x9d, 0xe9, 0xce, 0xc4, 0x1a, 0x4b, 0x6f, 0x7c, 0x82, 0x82, 0x8f, 0x23,
	0xde, 0xf7, 0x32, 0x20, 0x82, 0x08, 0x16, 0x49, 0x7c, 0x10, 0xd9, 0xd9, 0xcd, 0xe6, 0x47, 0x4b,
	0x9a, 0x6c, 0xaf, 0x32, 0x39, 0x73, 0xce, 0xf7, 0x73, 0xe6, 0xcc, 0x2c, 0xdc, 0x29, 0xf3, 0x4a,
	0x85, 0x05, 0x65, 0x8f, 0xfb, 0x4c, 0xed, 0xf2, 0x60, 0x8b, 0x26, 0x81, 0x8a, 0xe7, 0x2b, 0xba,
	0x53, 0x65, 0x41, 0xcd, 0x12, 0x01, 0x57, 0x1c, 0xd3, 0xde, 0x5c, 0xeb, 0xf8, 0x40, 0x58, 0x6c,
	0xcc, 0xb8, 0xdc, 0xe5, 0xba, 0x96, 0x86, 0xab, 0x08, 0xc6, 0xb8, 0xe6, 0x72, 0xee, 0x6e, 0x33,
	0xea, 0x08, 0x8f, 0x3a, 0xbe, 0xcf, 0x95, 0xa3, 0x3c, 0xee, 0xcb, 0x78, 0x37, 0xd7, 0x47, 0x90,
	0xe0, 0xd2, 0x0b, 0xf3, 0xa3, 0x74, 0x72, 0x1d, 0xce, 0xbf, 0x0c, 0x25, 0x16, 0x94, 0x28, 0xb1,
	0x9d, 0x2a, 0x93, 0x0a, 0x4f, 0x41, 0xb6, 0x98, 0x9f, 0x45, 0xf3, 0xe8, 0xd6, 0x44, 0x29, 0x5b,
	0xcc, 0x13, 0x0b, 0x2e, 0xf7, 0xa4, 0xd8, 0xb5, 0x17, 0xbb, 0x3e, 0x0b, 0xf0, 0x0c, 0x8c, 0xe9,
	0x45, 0x9c, 0x1c, 0xfd, 0x21, 0x1e, 0x5c, 0x68, 0xe7, 0x4b, 0xc1, 0x7d, 0xc9, 0xf0, 0x2b, 0x18,
	0x5f, 0x8d, 0x89, 0x75, 0xf2, 0xd9, 0xa5, 0x47, 0xd6, 0x80, 0xdd, 0xb0, 0x5a, 0x00, 0xa5, 0x04,
	0x8a, 0xe0, 0x36, 0x95, 0x8c, 0xb5, 0x91, 0x6d, 0xb8, 0xd8, 0x11, 0x8b, 0xf9, 0x5f, 0xc3, 0x44,
	0xab, 0x48, 0xce, 0xa2, 0xf9, 0x91, 0x74, 0x02, 0xda, 0x58, 0xe4, 0x12, 0x4c, 0x6b, 0xb6, 0xc7,
	0xdc, 0x7f, 0xcf, 0x02, 0x19, 0xee, 0x3a, 0x8a, 0x11, 0x07, 0xae, 0xfe, 0x27, 0x9c, 0xc8, 0xb1,
	0x61, 0x34, 0x70, 0x14, 0x8b, 0xfa, 0x66, 0x5b, 0x87, 0x47, 0x73, 0x99, 0x9f, 0x47, 0x73, 0x0b,
	0xae, 0xa7, 0xde, 0x55, 0xd7, 0x43, 0x56, 0x5a, 0xe6, 0xb2, 0xc2, 0x65, 0xfc, 0x93, 0x93, 0x1b,
	0x5b, 0x54, 0xd5, 0x04, 0x93, 0x56, 0x9e, 0x95, 0x4b, 0xba, 0x96, 0x4c, 0xc7, 0x3e, 0x9f, 0x04,
	0x8c, 0x7d, 0x64, 0xab, 0x2c, 0xf0, 0xf8, 0x06, 0x59, 0x86, 0x2b, 0xff, 0x04, 0x13, 0xd6, 0x1b,
	0x70, 0x6e, 0x53, 0xc7, 0xd7, 0x84, 0xde, 0x88, 0x8f, 0x6d, 0x72, 0xb3, 0x23, 0x79, 0xe9, 0x60,
	0x1c, 0xc6, 0x34, 0x04, 0xfe, 0x8a, 0x60, 0xa4, 0xa0, 0x04, 0x5e, 0x1e, 0xb8, 0x51, 0x3d, 0xe3,
	0x62, 0xac, 0xa4, 0x40, 0x88, 0xb4, 0x93, 0xc5, 0x4f, 0xdf, 0xfe, 0x7c, 0xce, 0xde, 0xc5, 0xb7,
	0x69, 0x9f, 0xf9, 0x66, 0x4a, 0x48, 0xba, 0x57, 0xcc, 0xef, 0xe3, 0x3a, 0x02, 0x28, 0x28, 0xd1,
	0x1a, 0xd6, 0xa7, 0x69, 0x6d, 0xc4, 0x40, 0x86, 0x3d, 0x34, 0x50, 0x32, 0x8f, 0xe4, 0x81, 0xb6,
	0x43, 0x71, 0xae, 0x9f, 0x1d, 0x1e, 0x52, 0xd2, 0x3d, 0xcd, 0xbc, 0x8f, 0xbf, 0x20, 0x18, 0x0d,
	0x71, 0xf0, 0x4a, 0x1a, 0x0d, 0xd1, 0xa1, 0x9c, 0x86, 0x8d, 0x7b, 0xda, 0xc6, 0x02, 0xbe, 0x79,
	0x92, 0x53, 0xc1, 0xbf, 0x10, 0x4c, 0x75, 0x5f, 0x08, 0x9c, 0x1f, 0x4e, 0x44, 0x37, 0x8a, 0xf1,
	0xfc, 0x34, 0x50, 0x12, 0x53, 0x0f, 0xb5, 0xa9, 0x45, 0x4c, 0xfb, 0x99, 0x2a, 0x27, 0xf5, 0x6b,
	0xe1, 0x8d, 0xc4, 0xdf, 0x11, 0x4c, 0x76, 0x5e, 0x3c, 0x3c, 0x64, 0x8b, 0x3b, 0x31, 0x8c, 0x67,
	0xe9, 0x31, 0x06, 0x9f, 0xba, 0xae, 0x67, 0xc2, 0x7e, 0x7b, 0xd8, 0x30, 0x51, 0xbd, 0x61, 0xa2,
	0xdf, 0x0d, 0x13, 0x1d, 0x34, 0xcd, 0x4c, 0xbd, 0x69, 0x66, 0x7e, 0x34, 0xcd, 0xcc, 0x1b, 0xbb,
	0xeb, 0xc5, 0x3a, 0x0e, 0xb2, 0x15, 0xf8, 0xd0, 0xc3, 0xa2, 0x5f, 0xb4, 0xf5, 0x33, 0xfa, 0x43,
	0x74, 0xff, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbb, 0x55, 0xa9, 0xb3, 0x4a, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a Etp by id.
	Etp(ctx context.Context, in *QueryEtpRequest, opts ...grpc.CallOption) (*QueryEtpResponse, error)
	EtpByOwner(ctx context.Context, in *QueryEtpRequestByOwner, opts ...grpc.CallOption) (*QueryEtpsResponse, error)
	Etps(ctx context.Context, in *QueryEtpsRequest, opts ...grpc.CallOption) (*QueryEtpsResponse, error)
	ConversionRate(ctx context.Context, in *QueryConversionRate, opts ...grpc.CallOption) (*QueryConversionRateResponse, error)
	FreezePeriod(ctx context.Context, in *QueryFreezePeriod, opts ...grpc.CallOption) (*QueryFreezePeriodResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Etp(ctx context.Context, in *QueryEtpRequest, opts ...grpc.CallOption) (*QueryEtpResponse, error) {
	out := new(QueryEtpResponse)
	err := c.cc.Invoke(ctx, "/commercionetwork.commercionetwork.commerciomint.Query/Etp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EtpByOwner(ctx context.Context, in *QueryEtpRequestByOwner, opts ...grpc.CallOption) (*QueryEtpsResponse, error) {
	out := new(QueryEtpsResponse)
	err := c.cc.Invoke(ctx, "/commercionetwork.commercionetwork.commerciomint.Query/EtpByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Etps(ctx context.Context, in *QueryEtpsRequest, opts ...grpc.CallOption) (*QueryEtpsResponse, error) {
	out := new(QueryEtpsResponse)
	err := c.cc.Invoke(ctx, "/commercionetwork.commercionetwork.commerciomint.Query/Etps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ConversionRate(ctx context.Context, in *QueryConversionRate, opts ...grpc.CallOption) (*QueryConversionRateResponse, error) {
	out := new(QueryConversionRateResponse)
	err := c.cc.Invoke(ctx, "/commercionetwork.commercionetwork.commerciomint.Query/ConversionRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FreezePeriod(ctx context.Context, in *QueryFreezePeriod, opts ...grpc.CallOption) (*QueryFreezePeriodResponse, error) {
	out := new(QueryFreezePeriodResponse)
	err := c.cc.Invoke(ctx, "/commercionetwork.commercionetwork.commerciomint.Query/FreezePeriod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a Etp by id.
	Etp(context.Context, *QueryEtpRequest) (*QueryEtpResponse, error)
	EtpByOwner(context.Context, *QueryEtpRequestByOwner) (*QueryEtpsResponse, error)
	Etps(context.Context, *QueryEtpsRequest) (*QueryEtpsResponse, error)
	ConversionRate(context.Context, *QueryConversionRate) (*QueryConversionRateResponse, error)
	FreezePeriod(context.Context, *QueryFreezePeriod) (*QueryFreezePeriodResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Etp(ctx context.Context, req *QueryEtpRequest) (*QueryEtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Etp not implemented")
}
func (*UnimplementedQueryServer) EtpByOwner(ctx context.Context, req *QueryEtpRequestByOwner) (*QueryEtpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EtpByOwner not implemented")
}
func (*UnimplementedQueryServer) Etps(ctx context.Context, req *QueryEtpsRequest) (*QueryEtpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Etps not implemented")
}
func (*UnimplementedQueryServer) ConversionRate(ctx context.Context, req *QueryConversionRate) (*QueryConversionRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConversionRate not implemented")
}
func (*UnimplementedQueryServer) FreezePeriod(ctx context.Context, req *QueryFreezePeriod) (*QueryFreezePeriodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FreezePeriod not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Etp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Etp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commercionetwork.commercionetwork.commerciomint.Query/Etp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Etp(ctx, req.(*QueryEtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EtpByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEtpRequestByOwner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EtpByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commercionetwork.commercionetwork.commerciomint.Query/EtpByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EtpByOwner(ctx, req.(*QueryEtpRequestByOwner))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Etps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEtpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Etps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commercionetwork.commercionetwork.commerciomint.Query/Etps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Etps(ctx, req.(*QueryEtpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ConversionRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryConversionRate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ConversionRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commercionetwork.commercionetwork.commerciomint.Query/ConversionRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ConversionRate(ctx, req.(*QueryConversionRate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FreezePeriod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFreezePeriod)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FreezePeriod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commercionetwork.commercionetwork.commerciomint.Query/FreezePeriod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FreezePeriod(ctx, req.(*QueryFreezePeriod))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "commercionetwork.commercionetwork.commerciomint.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Etp",
			Handler:    _Query_Etp_Handler,
		},
		{
			MethodName: "EtpByOwner",
			Handler:    _Query_EtpByOwner_Handler,
		},
		{
			MethodName: "Etps",
			Handler:    _Query_Etps_Handler,
		},
		{
			MethodName: "ConversionRate",
			Handler:    _Query_ConversionRate_Handler,
		},
		{
			MethodName: "FreezePeriod",
			Handler:    _Query_FreezePeriod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commercionetwork/commerciomint/query.proto",
}

func (m *QueryEtpRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEtpRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEtpRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEtpRequestByOwner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEtpRequestByOwner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEtpRequestByOwner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEtpResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEtpResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEtpResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Position != nil {
		{
			size, err := m.Position.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryEtpsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEtpsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEtpsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryEtpsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryEtpsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryEtpsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryConversionRate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConversionRate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConversionRate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryConversionRateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryConversionRateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryConversionRateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Rate.Size()
		i -= size
		if _, err := m.Rate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryFreezePeriod) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFreezePeriod) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFreezePeriod) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryFreezePeriodResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFreezePeriodResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFreezePeriodResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FreezePeriod) > 0 {
		i -= len(m.FreezePeriod)
		copy(dAtA[i:], m.FreezePeriod)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.FreezePeriod)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryEtpRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEtpRequestByOwner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEtpResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Position != nil {
		l = m.Position.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryEtpsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryEtpsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryConversionRate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryConversionRateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Rate.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryFreezePeriod) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryFreezePeriodResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FreezePeriod)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryEtpRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEtpRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEtpRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEtpRequestByOwner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEtpRequestByOwner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEtpRequestByOwner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEtpResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEtpResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEtpResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Position == nil {
				m.Position = &Position{}
			}
			if err := m.Position.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEtpsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEtpsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEtpsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryEtpsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryEtpsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryEtpsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, &Position{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConversionRate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConversionRate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConversionRate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryConversionRateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryConversionRateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryConversionRateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Rate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFreezePeriod) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFreezePeriod: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFreezePeriod: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFreezePeriodResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFreezePeriodResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFreezePeriodResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FreezePeriod", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FreezePeriod = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
